### ISSUE TITLE
GetItem_DynamicAndTyped_SimpleType failed on german test system

### ISSUE THREAD

**Issue by braegelno5** [ttu/json-flatfile-datastore#28]
On a german system (windows client OS) the 
test GetItem_DynamicAndTyped_SimpleType failed,

- the internal _jsonData is correct build
- but the _jsonData["myValue"]  gives 2,1 not 2.1
- so the JsonConvert.DeserializeObject runs into a new exception type
- after shown changes the test fails not anymore

_JsonFlatFileDataStore.DataStore_:
``private dynamic SingleDynamicItemReadConverter(JToken e)
{
	try
	{
		// As we don't want to return JObject when using dynamic, JObject will be converted to ExpandoObject
		return JsonConvert.DeserializeObject<ExpandoObject>(e.ToString(), _converter) as dynamic;
	}
	catch (Exception ex) when (ex is InvalidCastException _**|| ex is JsonReaderException**_)
	{
		return e.ToObject<object>();
	}
}

**Comment by ttu** [comment]
@braegelno5  Thanks for bringing this issue up and sorry that forgot to reply earlier.

Added culture info to the single item converter, does that help? I think it would maybe be better solution so then converter would return ExpandoObject, instead of JObject that catch will return.

Although not sure that forcing to en-US culture is the right thing to do in the end. Do you have any opinion?

Also added double rating to movies collection, so can you run all tests again and check if you get error from other converters?

Branch: https://github.com/ttu/json-flatfile-datastore/tree/fix-SingleDynamicItemReadConverter

**Comment by ttu** [comment]
Sorry. First fix didn't work. I changed the culture from the wrong place and thought that the code fix did work.

So fix was in the end pretty simple. JToken ToString() is not culture invariant, so when using string.Format culture can be defined to invariant.
```cs
// var content = e.ToString();
var content = string.Format(CultureInfo.InvariantCulture, "{0}", e);
return JsonConvert.DeserializeObject<ExpandoObject>(content, _converter) as dynamic;
```

Conversion problem was only with value types, not with objects, so decided to add some handling based on JToken types, so arrays etc. are now handled correctly. Propably there is still cases that are not handled correctly.

**Comment by ttu** [comment]
@braegelno5 Merged this fix to master. We can reopen this issue if  you still get this error.
