### ISSUE TITLE
Dynamic update of child items

### ISSUE THREAD

**Issue by Pete1138** [ttu/json-flatfile-datastore#47]
Please could you help me and tell me if what I am trying to achieve is possible; finding child elements and updating them.

```
{
  "Parents": [
    {
      "Name": "Parent1",
      "Children": [
        {
          "Name": "Parent1Child1",
          "Description": "P1-C1"
        },
        {
          "Name": "Parent1Child2",
          "Description": "P1-C2"
        },
      ]
    },
    {
      "Name": "Parent2",
      "Children": [
        {
          "Name": "Parent2Child1",
          "Description": "P2-C1"
        }
      ]
    }
  ]
}
```

```
var store = new DataStore(@"C:\test.json");
var parents = store.GetCollection("Parents");
var parent1 = parents
			.AsQueryable()
			.FirstOrDefault(p => p.Name == "Parent1");
var children = parent1.Children;
var child2 = ((IEnumerable<dynamic>)children).FirstOrDefault(t => t.Name == "Parent1Child2");
	
((dynamic)child2).Description = "UPDATED";
	
parents.UpdateOneAsync("Parent1", child2).GetAwaiter().GetResult();
```

This updates the correct item (parent1 child 2), but it's not saved back to the test.json file

**Comment by ttu** [comment]
Hi,

By default DataStore expects json to be in lower camelcase and that id field is named `id`. So in your case you need to configure it differently

```cs
var store = new DataStore(newFilePath, useLowerCamelCase: false, keyProperty: "Name");
```

When you update the item you can use Replace if you provide the whole object or if you create a patch item that has only the changed data then Update is better. Also if you need sync method then its better to use ReplaceOne instead of ReplaceOneAsync.

```cs
await parents.ReplaceOneAsync("Parent1", parent1);

// or

parensts.ReplaceOne("Parent1", parent1);
```

If you have more questions, just ask :) Based on these I might need to update the documenation littlebit more (maybe add getting started segment).
